# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 647)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#centralwidget, #mainBodyContent, QLineEdit{\n"
"    background-color: #1b1b27;\n"
"}\n"
"\n"
"#header, #mainBody{\n"
"    background-color: #27263c;\n"
"}\n"
"\n"
"#toggleRightMenuBtn{\n"
"    border: 2px solid #cc5bce;\n"
"    border-radius: 17px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#saveUserDataBtn{\n"
"    background-color: #cc5bce;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #1b1b27;\n"
"    border-left: 3px solid #cc5bce;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    padding: 5px 10px;\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.header)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toggleLeftMenuBtn = QtWidgets.QPushButton(self.frame_2)
        self.toggleLeftMenuBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleLeftMenuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleLeftMenuBtn.setIcon(icon)
        self.toggleLeftMenuBtn.setIconSize(QtCore.QSize(32, 32))
        self.toggleLeftMenuBtn.setObjectName("toggleLeftMenuBtn")
        self.horizontalLayout_4.addWidget(self.toggleLeftMenuBtn, 0, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.toggleRightMenuBtn = QtWidgets.QPushButton(self.frame)
        self.toggleRightMenuBtn.setMinimumSize(QtCore.QSize(38, 38))
        self.toggleRightMenuBtn.setMaximumSize(QtCore.QSize(38, 38))
        self.toggleRightMenuBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleRightMenuBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleRightMenuBtn.setIcon(icon2)
        self.toggleRightMenuBtn.setIconSize(QtCore.QSize(32, 32))
        self.toggleRightMenuBtn.setObjectName("toggleRightMenuBtn")
        self.horizontalLayout_3.addWidget(self.toggleRightMenuBtn)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        self.mainBody.setObjectName("mainBody")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainBody)
        self.horizontalLayout_2.setContentsMargins(0, 11, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftMenu = QtWidgets.QWidget(self.mainBody)
        self.leftMenu.setEnabled(True)
        self.leftMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftMenu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.leftMenu)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.homeBtn = QtWidgets.QPushButton(self.frame_3)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon3)
        self.homeBtn.setIconSize(QtCore.QSize(32, 32))
        self.homeBtn.setCheckable(True)
        self.homeBtn.setChecked(True)
        self.homeBtn.setAutoExclusive(True)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_5.addWidget(self.homeBtn)
        self.productsBtn = QtWidgets.QPushButton(self.frame_3)
        self.productsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/pizza.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.productsBtn.setIcon(icon4)
        self.productsBtn.setIconSize(QtCore.QSize(32, 32))
        self.productsBtn.setCheckable(True)
        self.productsBtn.setChecked(False)
        self.productsBtn.setAutoExclusive(True)
        self.productsBtn.setObjectName("productsBtn")
        self.verticalLayout_5.addWidget(self.productsBtn)
        self.verticalLayout_4.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setAutoExclusive(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.leftMenu)
        self.mainBodyContent = QtWidgets.QWidget(self.mainBody)
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainBodyContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainBodyContent)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.label_4 = QtWidgets.QLabel(self.homePage)
        self.label_4.setGeometry(QtCore.QRect(100, 160, 451, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.homePage)
        self.productsPage = QtWidgets.QWidget()
        self.productsPage.setObjectName("productsPage")
        self.label_3 = QtWidgets.QLabel(self.productsPage)
        self.label_3.setGeometry(QtCore.QRect(130, 170, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.productsPage)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.mainBodyContent)
        self.rightMenu = QtWidgets.QWidget(self.mainBody)
        self.rightMenu.setMinimumSize(QtCore.QSize(200, 0))
        self.rightMenu.setObjectName("rightMenu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rightMenu)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.rightMenu)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(70, 70))
        self.label_2.setMaximumSize(QtCore.QSize(70, 70))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/resources/edit.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_9.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_9.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_9.addWidget(self.lineEdit_3)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.saveUserDataBtn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saveUserDataBtn.setFont(font)
        self.saveUserDataBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveUserDataBtn.setObjectName("saveUserDataBtn")
        self.verticalLayout_8.addWidget(self.saveUserDataBtn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.rightMenu)
        self.verticalLayout.addWidget(self.mainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EatFit"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.homeBtn.setText(_translate("MainWindow", "Главная"))
        self.productsBtn.setText(_translate("MainWindow", "Продукты"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.label_4.setText(_translate("MainWindow", "Здесь отображается выбранный день"))
        self.label_3.setText(_translate("MainWindow", "Здесь изменяются продукты"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Вес"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Рост"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Возраст"))
        self.saveUserDataBtn.setText(_translate("MainWindow", "Сохранить"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
